// ─────────────────────────────────────────────────────────────────────────
//  Perfume image system
//  -----------------------------------------------------------------------
//  Dual-source: real product photos (uploaded to /public/perfumes/) when
//  available, otherwise an inline SVG placeholder with a brand-specific
//  bottle silhouette and brand monogram.
//
//  Real images take precedence — see `perfume-images.ts` for the manifest
//  generated by the admin upload flow at /admin/images.
// ─────────────────────────────────────────────────────────────────────────

import { perfumeImageManifest } from "./perfume-images";

// ────────────── Family palettes (background tints) ──────────────
type FamilyKey =
  | "blumig" | "blumig-oriental" | "blumig-amber" | "blumig-frisch"
  | "oriental" | "oriental-holzig" | "oriental-vanille" | "oriental-amber" | "oriental-blumig" | "oriental-wuerzig"
  | "holzig" | "holzig-aromatisch" | "holzig-wuerzig" | "holzig-frisch" | "holzig-blumig" | "holzig-aquatisch"
  | "frisch" | "frisch-wuerzig" | "fougere" | "chypre" | "chypre-blumig" | "chypre-fruchtig"
  | "fruchtig" | "fruchtig-chypre" | "fruchtig-gourmand"
  | "ledrig" | "ledrig-wuerzig" | "gourmand" | "aquatisch" | "aquatisch-aromatisch"
  | "aromatisch-fougere" | "aromatisch-frisch"
  | "default";

const FAMILY_PALETTES: Record<FamilyKey, { from: string; to: string; accent: string }> = {
  "blumig":               { from: "#f6ece5", to: "#e8d4c8", accent: "#b88c7a" },
  "blumig-oriental":      { from: "#efe2da", to: "#d8c0a8", accent: "#9b7456" },
  "blumig-amber":         { from: "#f5e9d2", to: "#e3c89a", accent: "#a87a3c" },
  "blumig-frisch":        { from: "#eef0e8", to: "#dce0d0", accent: "#7d8a72" },
  "oriental":             { from: "#efdcc0", to: "#d4b384", accent: "#8b5e2a" },
  "oriental-holzig":      { from: "#e8d4b0", to: "#c8a070", accent: "#7a4a1c" },
  "oriental-vanille":     { from: "#f0e2c4", to: "#d8b886", accent: "#8e6128" },
  "oriental-amber":       { from: "#eed7b0", to: "#d4ad72", accent: "#85571f" },
  "oriental-blumig":      { from: "#f0dcc4", to: "#d8b88a", accent: "#8a5e2e" },
  "oriental-wuerzig":     { from: "#e8d2b2", to: "#c89870", accent: "#7c4a1f" },
  "holzig":               { from: "#ece2d0", to: "#cfb98e", accent: "#7d5a30" },
  "holzig-aromatisch":    { from: "#e6e8df", to: "#c8ccba", accent: "#6e7560" },
  "holzig-wuerzig":       { from: "#ebdcc0", to: "#cba87a", accent: "#7d4f1f" },
  "holzig-frisch":        { from: "#e6ece0", to: "#c8d2b8", accent: "#6e7858" },
  "holzig-blumig":        { from: "#ece0c8", to: "#cdb38c", accent: "#7e5a35" },
  "holzig-aquatisch":     { from: "#e2e6e0", to: "#bcc6b8", accent: "#5a6f5a" },
  "frisch":               { from: "#e9eeec", to: "#cdd6d2", accent: "#5c726a" },
  "frisch-wuerzig":       { from: "#ece8de", to: "#d2cab7", accent: "#766a4f" },
  "fougere":              { from: "#e6ebe0", to: "#c4cdb8", accent: "#5e6e4a" },
  "chypre":               { from: "#ece4d0", to: "#cfbe96", accent: "#7c623c" },
  "chypre-blumig":        { from: "#eee0d0", to: "#d4b698", accent: "#7e5a3a" },
  "chypre-fruchtig":      { from: "#eedcc8", to: "#d2b288", accent: "#7a5430" },
  "fruchtig":             { from: "#f4e8d2", to: "#e2c898", accent: "#a36a30" },
  "fruchtig-chypre":      { from: "#efdcc0", to: "#d4b07a", accent: "#825030" },
  "fruchtig-gourmand":    { from: "#f5e0c8", to: "#e0b888", accent: "#8e5826" },
  "ledrig":               { from: "#e6d5c0", to: "#bf9874", accent: "#6e3f1f" },
  "ledrig-wuerzig":       { from: "#e2cfb6", to: "#b8906a", accent: "#683818" },
  "gourmand":             { from: "#f0dec5", to: "#dab891", accent: "#8b572c" },
  "aquatisch":            { from: "#e3eaee", to: "#bccad3", accent: "#4a6a7a" },
  "aquatisch-aromatisch": { from: "#e5ece8", to: "#c0d0c8", accent: "#506e60" },
  "aromatisch-fougere":   { from: "#e8eee0", to: "#cad6b8", accent: "#5e7048" },
  "aromatisch-frisch":    { from: "#e6ece6", to: "#c8d2c4", accent: "#5e7060" },
  "default":              { from: "#efe9df", to: "#d6cdbb", accent: "#7d6f5a" },
};

function familyKey(family?: string): FamilyKey {
  if (!family) return "default";
  const f = family.toLowerCase();
  // Exact-ish multi-word matches first
  if (f.includes("blumig") && f.includes("oriental")) return "blumig-oriental";
  if (f.includes("blumig") && f.includes("amber")) return "blumig-amber";
  if (f.includes("blumig") && f.includes("frisch")) return "blumig-frisch";
  if (f.includes("oriental") && f.includes("vanille")) return "oriental-vanille";
  if (f.includes("oriental") && f.includes("amber")) return "oriental-amber";
  if (f.includes("oriental") && f.includes("holzig")) return "oriental-holzig";
  if (f.includes("oriental") && f.includes("blumig")) return "oriental-blumig";
  if (f.includes("oriental") && f.includes("würz")) return "oriental-wuerzig";
  if (f.includes("holzig") && f.includes("würz")) return "holzig-wuerzig";
  if (f.includes("holzig") && f.includes("aroma")) return "holzig-aromatisch";
  if (f.includes("holzig") && f.includes("frisch")) return "holzig-frisch";
  if (f.includes("holzig") && f.includes("blumig")) return "holzig-blumig";
  if (f.includes("holzig") && f.includes("aqua")) return "holzig-aquatisch";
  if (f.includes("chypre") && f.includes("blumig")) return "chypre-blumig";
  if (f.includes("chypre") && f.includes("frucht")) return "chypre-fruchtig";
  if (f.includes("frucht") && f.includes("chypre")) return "fruchtig-chypre";
  if (f.includes("frucht") && f.includes("gourmand")) return "fruchtig-gourmand";
  if (f.includes("aqua") && f.includes("aroma")) return "aquatisch-aromatisch";
  if (f.includes("aroma") && (f.includes("fougère") || f.includes("fougere"))) return "aromatisch-fougere";
  if (f.includes("aroma") && f.includes("frisch")) return "aromatisch-frisch";
  if (f.includes("frisch") && f.includes("würz")) return "frisch-wuerzig";
  if (f.includes("ledrig") && f.includes("würz")) return "ledrig-wuerzig";
  // Single-word
  if (f.includes("blumig")) return "blumig";
  if (f.includes("oriental")) return "oriental";
  if (f.includes("holzig")) return "holzig";
  if (f.includes("frisch")) return "frisch";
  if (f.includes("fougère") || f.includes("fougere")) return "fougere";
  if (f.includes("chypre")) return "chypre";
  if (f.includes("frucht")) return "fruchtig";
  if (f.includes("ledrig") || f.includes("leder")) return "ledrig";
  if (f.includes("gourmand")) return "gourmand";
  if (f.includes("aqua")) return "aquatisch";
  return "default";
}

export function getFamilyGradient(family?: string): string {
  const p = FAMILY_PALETTES[familyKey(family)];
  return `linear-gradient(135deg, ${p.from} 0%, ${p.to} 100%)`;
}

export function getFamilyAccent(family?: string): string {
  return FAMILY_PALETTES[familyKey(family)].accent;
}

// ────────────── Bottle silhouettes (paths over a 400×600 viewport) ──────────────
// Each bottle is centered horizontally (cx=200), drawn between y≈140 and y≈480.
type BottleRenderer = (accent: string) => string;

const BOTTLES: Record<string, BottleRenderer> = {
  // ── classic rectangular Tom Ford / Chanel / Versace
  classic: (a) => `
    <rect x="178" y="118" width="44" height="32" rx="3"
      fill="${a}" fill-opacity="0.34"/>
    <rect x="184" y="148" width="32" height="6"
      fill="${a}" fill-opacity="0.22"/>
    <rect x="130" y="156" width="140" height="320" rx="10"
      fill="${a}" fill-opacity="0.20" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>
    <rect x="130" y="320" width="140" height="156" rx="10"
      fill="${a}" fill-opacity="0.16"/>
    <rect x="158" y="350" width="84" height="44"
      fill="white" fill-opacity="0.30" stroke="${a}" stroke-opacity="0.22" stroke-width="0.8"/>`,

  // ── rounded-shoulder (Dior Sauvage, YSL, Creed)
  rounded: (a) => `
    <rect x="180" y="120" width="40" height="34" rx="6"
      fill="${a}" fill-opacity="0.34"/>
    <path d="M138 156 Q200 144 262 156 L262 472 Q262 478 256 478 L144 478 Q138 478 138 472 Z"
      fill="${a}" fill-opacity="0.20" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>
    <path d="M138 320 Q200 312 262 320 L262 472 Q262 478 256 478 L144 478 Q138 478 138 472 Z"
      fill="${a}" fill-opacity="0.16"/>
    <ellipse cx="200" cy="382" rx="46" ry="22"
      fill="white" fill-opacity="0.28"/>`,

  // ── apothecary cylinder (Le Labo, Diptyque, Byredo)
  apothecary: (a) => `
    <rect x="186" y="118" width="28" height="22" rx="2"
      fill="${a}" fill-opacity="0.32"/>
    <rect x="172" y="140" width="56" height="14" rx="2"
      fill="${a}" fill-opacity="0.24"/>
    <rect x="138" y="158" width="124" height="318" rx="14"
      fill="${a}" fill-opacity="0.20" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>
    <rect x="158" y="248" width="84" height="120"
      fill="white" fill-opacity="0.32" stroke="${a}" stroke-opacity="0.22" stroke-width="0.8"/>
    <line x1="170" y1="282" x2="230" y2="282" stroke="${a}" stroke-opacity="0.30" stroke-width="0.8"/>
    <line x1="170" y1="296" x2="216" y2="296" stroke="${a}" stroke-opacity="0.25" stroke-width="0.6"/>`,

  // ── wide flacon (MFK Baccarat, Carolina Herrera, Burberry)
  flacon: (a) => `
    <rect x="170" y="106" width="60" height="36" rx="3"
      fill="${a}" fill-opacity="0.34"/>
    <rect x="186" y="142" width="28" height="22" rx="2"
      fill="${a}" fill-opacity="0.26"/>
    <path d="M124 178 Q124 166 138 166 L262 166 Q276 166 276 178 L276 470 Q276 478 268 478 L132 478 Q124 478 124 470 Z"
      fill="${a}" fill-opacity="0.20" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>
    <path d="M124 304 L276 304 L276 470 Q276 478 268 478 L132 478 Q124 478 124 470 Z"
      fill="${a}" fill-opacity="0.16"/>
    <line x1="138" y1="200" x2="262" y2="200" stroke="${a}" stroke-opacity="0.18" stroke-width="0.6"/>`,

  // ── modern minimalist (Hermès, Armani, Bvlgari, Lancôme)
  modern: (a) => `
    <rect x="184" y="116" width="32" height="28" rx="1"
      fill="${a}" fill-opacity="0.34"/>
    <rect x="148" y="144" width="104" height="14"
      fill="${a}" fill-opacity="0.18"/>
    <rect x="148" y="158" width="104" height="324"
      fill="${a}" fill-opacity="0.20" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>
    <rect x="148" y="320" width="104" height="162"
      fill="${a}" fill-opacity="0.14"/>`,

  // ── teardrop / decorative (Mugler Alien, Guerlain, Byredo Gypsy)
  teardrop: (a) => `
    <rect x="186" y="116" width="28" height="22" rx="2"
      fill="${a}" fill-opacity="0.34"/>
    <rect x="172" y="138" width="56" height="14" rx="2"
      fill="${a}" fill-opacity="0.24"/>
    <path d="M200 156 C 130 200, 116 320, 152 420 C 168 462, 232 462, 248 420 C 284 320, 270 200, 200 156 Z"
      fill="${a}" fill-opacity="0.20" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>
    <path d="M152 360 C 168 462, 232 462, 248 360 L 248 420 C 232 462, 168 462, 152 420 Z"
      fill="${a}" fill-opacity="0.18"/>`,

  // ── stiletto (Carolina Herrera Good Girl)
  stiletto: (a) => `
    <rect x="190" y="118" width="20" height="24" rx="2"
      fill="${a}" fill-opacity="0.34"/>
    <path d="M188 142 L212 142 L240 200 L240 460 Q240 478 224 478 L156 478 L156 410 L112 380 L156 380 L156 360 L188 200 Z"
      fill="${a}" fill-opacity="0.22" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>`,

  // ── star (Mugler Angel)
  star: (a) => `
    <rect x="186" y="120" width="28" height="20" rx="2"
      fill="${a}" fill-opacity="0.34"/>
    <path d="M200 152 L228 248 L328 248 L246 308 L274 404 L200 344 L126 404 L154 308 L72 248 L172 248 Z"
      transform="translate(0,40)"
      fill="${a}" fill-opacity="0.22" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>`,

  // ── torso (Jean Paul Gaultier Le Male)
  torso: (a) => `
    <ellipse cx="200" cy="156" rx="22" ry="18" fill="${a}" fill-opacity="0.28"/>
    <path d="M168 178 L232 178 L242 222 L256 280 L246 420 Q244 472 200 472 Q156 472 154 420 L144 280 L158 222 Z"
      fill="${a}" fill-opacity="0.22" stroke="${a}" stroke-opacity="0.22" stroke-width="1.2"/>
    <path d="M170 320 L230 320 L240 420 Q238 462 200 462 Q162 462 160 420 Z"
      fill="${a}" fill-opacity="0.16"/>`,
};

// Brand → bottle template mapping. Falls back to "classic".
const BRAND_BOTTLES: Record<string, keyof typeof BOTTLES> = {
  // brand SLUGs (markeSlug)
  "tom-ford": "classic",
  "chanel": "classic",
  "versace": "classic",
  "burberry": "classic",
  "dior": "rounded",
  "ysl": "rounded",
  "creed": "rounded",
  "armani": "modern",
  "hermes": "modern",
  "bvlgari": "modern",
  "lancome": "modern",
  "le-labo": "apothecary",
  "diptyque": "apothecary",
  "byredo": "apothecary",
  "mfk": "flacon",
  "carolina-herrera": "stiletto", // Good Girl is iconic
  "paco-rabanne": "modern",
  "gucci": "rounded",
  "guerlain": "teardrop",
  "mugler": "teardrop",        // Alien (Angel handled per-perfume below)
  "jpg": "torso",              // Le Male
};

// Per-perfume overrides for iconic shapes (slug → bottle key)
const PERFUME_BOTTLES: Record<string, keyof typeof BOTTLES> = {
  "angel": "star",
  "alien": "teardrop",
  "shalimar": "teardrop",
  "le-male": "torso",
  "good-girl": "stiletto",
  "bad-boy": "modern",
};

function pickBottle(slug?: string, brandSlug?: string): keyof typeof BOTTLES {
  if (slug && PERFUME_BOTTLES[slug]) return PERFUME_BOTTLES[slug];
  if (brandSlug && BRAND_BOTTLES[brandSlug]) return BRAND_BOTTLES[brandSlug];
  return "classic";
}

// ────────────── Encoding ──────────────
function encodeSvg(svg: string): string {
  return (
    "data:image/svg+xml;charset=utf-8," +
    encodeURIComponent(svg.replace(/\s+/g, " ").trim())
  );
}

function brandMonogram(brand: string): string {
  return brand
    .split(/\s+/)
    .filter((w) => w.length > 1 && !/^(de|du|la|le|el|of|the|by|&)$/i.test(w))
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join("");
}

// ────────────── Public API ──────────────
type GenerateOpts = {
  brand: string;
  name: string;
  family?: string;
  slug?: string;
  brandSlug?: string;
  width?: number;
  height?: number;
};

/** Generates an editorial SVG placeholder with a brand-specific bottle. */
export function generatePerfumeImage(opts: GenerateOpts): string {
  const { brand, family, slug, brandSlug, width = 600, height = 800 } = opts;
  const palette = FAMILY_PALETTES[familyKey(family)];
  const monogram = brandMonogram(brand);
  const bottleKind = pickBottle(slug, brandSlug);
  const bottle = BOTTLES[bottleKind](palette.accent);

  // The bottle paths are designed for a 400×600 internal coordinate system,
  // centered. We render at the requested aspect by stretching the viewBox.
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 600" width="${width}" height="${height}" preserveAspectRatio="xMidYMid slice">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="${palette.from}"/>
        <stop offset="100%" stop-color="${palette.to}"/>
      </linearGradient>
      <radialGradient id="vignette" cx="50%" cy="50%" r="65%">
        <stop offset="60%" stop-color="white" stop-opacity="0"/>
        <stop offset="100%" stop-color="${palette.accent}" stop-opacity="0.10"/>
      </radialGradient>
    </defs>
    <rect width="400" height="600" fill="url(#bg)"/>
    <rect width="400" height="600" fill="url(#vignette)"/>
    ${bottle}
    <text x="200" y="555" text-anchor="middle"
      font-family="Georgia, 'Playfair Display', serif"
      font-size="38" letter-spacing="0.08em"
      fill="${palette.accent}" fill-opacity="0.14"
      font-weight="500">${monogram}</text>
  </svg>`;
  return encodeSvg(svg);
}

export function generatePerfumeBanner(opts: Omit<GenerateOpts, "width" | "height">): string {
  return generatePerfumeImage({ ...opts, width: 1200, height: 800 });
}

// ────────────── Real-image lookup ──────────────
/** Returns the path under /perfumes/ if a real image was uploaded for this slug. */
export function realImageFor(slug: string): string | null {
  const ext = perfumeImageManifest[slug];
  return ext ? `/perfumes/${slug}.${ext}` : null;
}

/**
 * Convenience wrapper used everywhere a perfume image is needed.
 * Returns either the real product photo URL or a generated SVG fallback.
 */
export function imageFor(
  parfum: {
    marke: string;
    name: string;
    slug?: string;
    markeSlug?: string;
    duftfamilie?: string;
  },
  size: "card" | "banner" = "card",
): string {
  if (parfum.slug) {
    const real = realImageFor(parfum.slug);
    if (real) return real;
  }
  return size === "banner"
    ? generatePerfumeBanner({
        brand: parfum.marke,
        name: parfum.name,
        family: parfum.duftfamilie,
        slug: parfum.slug,
        brandSlug: parfum.markeSlug,
      })
    : generatePerfumeImage({
        brand: parfum.marke,
        name: parfum.name,
        family: parfum.duftfamilie,
        slug: parfum.slug,
        brandSlug: parfum.markeSlug,
      });
}

/** True if a real product photo has been uploaded for this perfume. */
export function hasRealImage(slug: string | undefined): boolean {
  if (!slug) return false;
  return !!perfumeImageManifest[slug];
}
